name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Build
        run: |
          # Get the ID and security principal of the current user account
          $myWindowsID = [System.Security.Principal.WindowsIdentity]::GetCurrent();
          $myWindowsPrincipal = New-Object System.Security.Principal.WindowsPrincipal($myWindowsID);

          # Get the security principal for the administrator role
          $adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator;

          # Check to see if we are currently running as an administrator
          if($myWindowsPrincipal.IsInRole($adminRole))
          {
              # We are running as an administrator, so change the title and background colour to indicate this
              $Host.UI.RawUI.WindowTitle = $myInvocation.MyCommand.Definition + "(Elevated)";
              $Host.UI.RawUI.BackgroundColor = "DarkBlue";
              Clear-Host;
          }
          else
          {
              # We are not running as an administrator, so relaunch as administrator
              Write-Host New Process

              # Create a new process object that starts PowerShell
              $newProcess = New-Object System.Diagnostics.ProcessStartInfo "PowerShell";

              # Specify the current script path and name as a parameter with added scope and support for scripts with spaces in it's path
              #-noexit
              $newProcess.Arguments =  "& iisreset /STOP;  Copy-Item ./release/* C:/inetpub/wwwroot/ -Recurse -Force; iisreset /START"

              # Indicate that the process should be elevated
              $newProcess.Verb = "runas";

              # Start the new process
              [System.Diagnostics.Process]::Start($newProcess);
              Write-Host Process Running
              $commandline = "& iisreset /STOP -Force;  Copy-Item ./release/* C:/inetpub/wwwroot/ -Recurse -Force; iisreset /START"

              Write-Host Executing $commandline;

              Invoke-Expression  $commandline

              # Exit from the current, unelevated, process
              Exit;
          }


          $commandline = "& iisreset /STOP;  Copy-Item ./release/* C:/inetpub/wwwroot/ -Recurse -Force; iisreset /START"

          Write-Host Executing $commandline;

          Invoke-Expression  $commandline

