name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # sets up .NET Core SDK 6.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Checkout
      uses: actions/checkout@v3
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: |
        #readlink -f TestMVCGithub.csproj 
        #cd /home/runner/work/TestMVC/TestMVC
        #ls -l "/home/runner/work/TestMVC/TestMVC/TestMVCGithub"
        dotnet publish "/home/runner/work/TestMVC/TestMVC/TestMVCGithub.sln" -c Release -o release --nologo
 
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
